[package]
name = "rusty-eca"
version = "0.1.0"
authors = ["Robert Peters <robert.peters.dd@gmail.com>"]

[dependencies]
piston = "0.33.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.39.0"
piston2d-opengl_graphics = "0.46.0"
fps_counter = "0.2.0"
palette = "0.2"
